# This file.yaml is dedicated to store the hyperparameters for each stage of the train process
# Includes parameters for each stage like: prepare, train, evaluate or whichever will be necessary
# Each set of hyperparameters will be readed by the defined script
# You can modify it to run a new pipeline (check the pipeline first to have a better performance)
data_acquisition:
  # for data acquisition stage
  path : 'tutorials/versioning/data.zip'
  repo : 'https://github.com/iterative/dataset-registry'

data_preprocess:
  # for data preprocessing path
  abspath : "data.zip"
  images_path : "data/train/**/*"

data_augmentation:
  # for data augmentation path 
  images_path : "data/train/"
  WithBrightnessChannels : [-50, 50]
  ChangeColorTemperature : [1100, 10000]
  AddToSaturation : [-40, 40]
  RemoveSaturation_mul: 0.25
  MotionBlur_k : 3

train:
  # for dataset image generation #
  num_classes: 2  #cats, dogs
  image_size: 224
  batch_size_training: 32
  batch_size_validation: 16

  # for dense layers (clasification block) #
  mid_neurons: 512
  mid_activation: relu
  drop_rate: 0.2
  end_neurons: 2
  end_activation: softmax

  # for model training parameters #
  class_mode: categorical
  optimizer: adam
  loss: categorical_crossentropy
  metric: accuracy
  number_epoch: 12

  #for paths
  abspath_data : "data"
  best_model_path : 'model/model_catdog.h5'
